version: '3.8'

services:
  talk-2-tables-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: talk-2-tables-mcp
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - TRANSPORT=streamable-http
      - LOG_LEVEL=INFO
      - DATABASE_PATH=test_data/sample.db
      - METADATA_PATH=resources/metadata.json
    volumes:
      # Mount custom database if needed
      - ./test_data:/app/test_data:ro
      - ./resources:/app/resources:ro
      # Optional: Mount custom database
      # - /path/to/your/database.db:/app/custom.db:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: talk-2-tables-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # Add SSL certificates if needed
      # - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - talk-2-tables-mcp
    restart: unless-stopped
    profiles:
      - production

  # Optional: Add monitoring with Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: talk-2-tables-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - talk-2-tables-mcp
    restart: unless-stopped
    profiles:
      - monitoring

networks:
  default:
    name: talk-2-tables-network